// AUTO-GENERATED by VARAKH EXECUTOR
// Run: npx playwright test submit.spec.js
const { test, expect } = require('@playwright/test');
const submission = require('./submission_payload.json');

test('submit project to devpost', async ({ page, context }) => {
  const cookieEnv = process.env.DEVPOST_SESSION_COOKIE;
  if (cookieEnv) { await context.addCookies(JSON.parse(cookieEnv)); }
  if (submission.platform === 'lablab') {
    await page.goto('https://lablab.ai/ai-hackathons');
    await page.waitForLoadState('networkidle');
    const submitBtn = page.locator('text=/submit|create.*project|new.*submission/i').first();
    if (await submitBtn.isVisible()) await submitBtn.click();
    await page.fill('input[name*="title"]', submission.projectName);
    await page.fill('textarea[name*="description"]', submission.description);
    const githubInput = page.locator('input[name*="github"]');
    if (await githubInput.isVisible()) await githubInput.fill(submission.repoUrl);
    await page.locator('button[type="submit"]').first().click();
    await page.waitForLoadState('networkidle');
    await expect(page.locator('text=/submitted|success|thank/i')).toBeVisible({ timeout: 10000 });
  }
  if (submission.platform === 'devpost') {
    await page.goto('https://devpost.com/software/new');
    await page.waitForLoadState('networkidle');
    await page.fill('#software_title', submission.projectName);
    await page.fill('#software_tagline', submission.tagline);
    await page.fill('#software_about', submission.description);
    await page.locator('button:text(/save|submit/i)').first().click();
    await page.waitForLoadState('networkidle');
    await expect(page.url()).toContain('/software/');
  }
});